language: node_js
node_js:
  - 14

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel # build docker images
  - docker tag udagram-api-feed ahmakl/udagram-api-feed:v1 #tag docker images
  - docker tag udagram-api-user ahmakl/udagram-api-user:v1
  - docker tag reverseproxy ahmakl/reverseproxy:v1
  - docker tag udagram-frontend ahmakl/udagram-frontend:local

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ahmakl/udagram-api-feed:v1
  - docker push ahmakl/udagram-api-user:v1
  - docker push ahmakl/reverseproxy:v1
  - docker push ahmakl/udagram-frontend:local